name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Mengambil seluruh history agar tidak memicu error 'shallow update'

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "raihanfaisalyusuf@gmail.com"
          git config --global user.name "RaihanIDN"
          
          # 1. Bersihkan jejak pelacakan LFS lama jika ada yang nyangkut di cache lokal
          git lfs untrack "static/*.png" --allow-empty || true
          rm -f .gitattributes || true
          
          # 2. Hapus file biner static secara fisik di runner
          rm -rf static/
          
          # 3. Commit penghapusan aset biner ke dalam history Git yang sudah ada
          git add .
          git commit -m "Cleanup and purge binary files for HF sync" || true
          
          # 4. Paksa push (force) untuk menimpa history kotor di Hugging Face dengan history baru yang bersih
          git remote add hf https://RaihanID:$HF_TOKEN@huggingface.co/spaces/RaihanID/resepku-golang || true
          git push --force hf main
