name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "raihanfaisalyusuf@gmail.com"
          git config --global user.name "RaihanIDN"
          
          # Trik jitu: Hapus folder static secara lokal & commit sebelum push ke HF
          git rm -rf static/ --cached || true
          rm -rf static/
          git add .
          git commit -m "Remove binary files for Hugging Face bypass" || true
          
          git remote add hf https://RaihanID:$HF_TOKEN@huggingface.co/spaces/RaihanID/resepku-golang
          git push --force hf main
